### PR TITLE
Pull Request for review #6

### PR DESCRIPTION
**Pull request by shreyataneja**

### CODE REVIEW

**Review by suhani2405 — CHANGES_REQUESTED** [review]
source files and header files must have doxygen syntax for commenting

**Comment by shreyataneja** [comment]
The comments are pas er the coding conventions. Mentioned on CU LEarn by the professor.
 Dyoxgen was an option not a mandatory thing to do. We are not using Doxygen documentation.
That is why the comments are not as per the Dyoxgen conventions.

**Comment by sidbk01** [comment]
@shreyataneja 

> Guidelines for code comments:
> 
> 1. Anyone reading the comments can easily understand the design and purpose of the code.
> 2. Consistency of the comment style. We will use /* */
> 3. Every file should have a comment at the top describing its contents in a general way
> 4. You need to use Doxigen notation (the one that matches style /* */)
> 5. Punctuation, spelling, and grammar are important.
> 
> You should have at least one detailed description, one brief description, comments that would not be included in the documentation (when generated automatically from the source code), one detailed description after member,  one brief description after member. You need to write comments for all the functions according to Doxigen notation

According to the guidelines provided on CuLearn, doxygen notation must be used.

**Comment by AnkitVig** [comment]
Doxigen Conventions added. As per the coding conventions

**Comment by suhani2405** [comment]
> Doxigen Conventions added. As per the coding conventions

Changes were made as requested but you haven't used the brief or detailed descriptions syntax for the function comments. We are approving it so you can go ahead but do note that the Prof. might look for them when grading.

**Review by suhani2405 — APPROVED** [review]

**Comment by AnkitVig** [comment]
We are not using Doxigen so these keywords won't make any sense. But we will consider your advice. Thanks for the review.

**Comment by sidbk01** [comment]
> We are not using Doxigen so these keywords won't make any sense. But we will consider your advice. Thanks for the review.

Alright. I ran the code and it works as it should and your group requirements have been met.

But you need to provide instructions for compiling/running the program on different OSs in your readme properly. (As it's possible to run a Linux shell on Windows using the WSL feature.) Also, when cloning or downloading your repo, the gsl folder in lib is empty. This will lead to compiling errors when compiling on Windows due to missing files in gsl folder so you need to add instructions for getting the GSL Library for the user. 

Otherwise, the program runs perfectly.

**Pull request closed without merging**
